extern crate self as appdb;

/// Authentication helpers for bootstrapping the embedded database.
pub mod auth;
/// Database runtime setup and global handle access.
pub mod connection;
/// Encryption helpers and key-provider abstractions.
pub mod crypto;
/// Library error types.
pub mod error;
/// Graph relation helpers built on top of SurrealDB relation tables.
pub mod graph;
/// Model metadata, schema registration, and relation metadata.
pub mod model;
/// Common re-exports for application code.
pub mod prelude;
/// Raw and builder-style query helpers.
pub mod query;
/// CRUD repository layer.
pub mod repository;
/// Serde helpers for ids and SurrealDB-friendly encoding.
pub mod serde_utils;
/// Explicit transaction runner helpers.
pub mod tx;

pub use appdb_macros::Sensitive;
pub use auth::*;
pub use connection::*;
pub use crypto::*;
pub use error::*;
pub use graph::*;
pub use repository::*;
pub use serde_utils::id::*;
pub use tx::*;

/// Trait implemented by encrypted domain types generated by `#[derive(Sensitive)]`.
pub trait Sensitive: Sized {
    /// The encrypted representation paired with this plaintext type.
    type Encrypted;

    /// Encrypts the value into its generated encrypted representation.
    fn encrypt(
        &self,
        context: &crate::crypto::CryptoContext,
    ) -> Result<Self::Encrypted, crate::crypto::CryptoError>;

    /// Decrypts a generated encrypted value back into the plaintext type.
    fn decrypt(
        encrypted: &Self::Encrypted,
        context: &crate::crypto::CryptoContext,
    ) -> Result<Self, crate::crypto::CryptoError>;
}
